# Do not modify this file!  It was generated by 'nixos-generate-config'
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a195ab6b-a58c-4e49-a0e0-0502996ecec5";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/472D-76B5";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/mnt/nas" = {
    device = "//nas.danielpereira.xyz/storage-share";
    fsType = "cifs";
    options = [
      "credentials=/home/daniel/.smbcredentials"
      "uid=1000"
      "gid=100"
      "iocharset=utf8"
      "_netdev"
      "nofail"
      "noauto"
      "x-systemd.automount"
      "x-systemd.idle-timeout=600"
      "x-systemd.requires=network-online.target"
      "x-systemd.after=network-online.target"
      "vers=3.0"
    ];
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/c2cfe6b9-bc41-45de-a3b3-ed679a0d46ca"; } ];

  services.udev.extraHwdb = ''
    evdev:input:*:name:TPPS/2 Elan TrackPoint
     KEYBOARD_KEY_273=reserved
  '';

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
