# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/44ef7b39-0f7c-478f-942b-a649a925b7ab";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DCF4-C238";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

	fileSystems."/mnt/bench" = {
		device = "/dev/disk/by-uuid/da444541-e215-459f-9507-64ea32d7a707";
		fsType = "ext4";
	};

  fileSystems."/mnt/nas" = {
    device = "//nas.danielpereira.xyz/storage-share";
    fsType = "cifs";
    options = [
      "credentials=/home/daniel/.smbcredentials"
      "uid=1000"
      "gid=100"
      "iocharset=utf8"
      "_netdev"
      "nofail"

      "noauto"
      "x-systemd.automount"
      "x-systemd.idle-timeout=600"

      "x-systemd.requires=network-online.target"
      "x-systemd.after=network-online.target"

      "vers=3.0"
    ];
  };


  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp11s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
