#------------------------------------------------------------------------------
# Oh-My-Zsh Configuration
#------------------------------------------------------------------------------
export ZSH="$HOME/.oh-my-zsh"

#------------------------------------------------------------------------------
# Plugins
#------------------------------------------------------------------------------
# Core plugins
plugins=(
git
zsh-z
asdf
docker-compose
extract
fzf-tab
# autoswitch_virtualenv
direnv
zsh-autosuggestions
)

# Source Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

#------------------------------------------------------------------------------
# Completion System
#------------------------------------------------------------------------------
autoload -U compinit && compinit
zstyle ':completion:*' menu select

#------------------------------------------------------------------------------
# Tool Configuration
#------------------------------------------------------------------------------

# TheFuck
eval $(thefuck --alias)

# Terminal
export TERM=xterm-256color
export COLORTERM=truecolor

#------------------------------------------------------------------------------
# Custom Configurations
#------------------------------------------------------------------------------
# Source custom configurations
source "$HOME/.dotfiles/zsh/aliases.zsh"
source "$HOME/.dotfiles/zsh/functions.zsh"

eval "$(starship init zsh)"
