#------------------------------------------------------------------------------
# Powerlevel10k Instant Prompt
#------------------------------------------------------------------------------
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# Suppress error message at boot
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

#------------------------------------------------------------------------------
# Oh-My-Zsh Configuration
#------------------------------------------------------------------------------
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

#------------------------------------------------------------------------------
# Plugins
#------------------------------------------------------------------------------
# Core plugins
plugins=(
git
asdf
docker-compose
extract
fzf-tab
# autoswitch_virtualenv
direnv
zsh-autosuggestions
zsh-z
)

# Source Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

#------------------------------------------------------------------------------
# Completion System
#------------------------------------------------------------------------------
autoload -U compinit && compinit
zstyle ':completion:*' menu select

#------------------------------------------------------------------------------
# Path Configuration
#------------------------------------------------------------------------------
export PATH="/opt/homebrew/opt/bison/bin:$PATH"
export PATH="/opt/homebrew/opt/ncurses/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"
export PATH="/Applications/Ghostty.app/Contents/MacOS:$PATH"

#------------------------------------------------------------------------------
# Tool Configuration
#------------------------------------------------------------------------------

# TheFuck
eval $(thefuck --alias)

# mise
eval "$(mise activate zsh)"

# Editor
export EDITOR=nvim

# Terminal
export TERM=xterm-256color
export COLORTERM=truecolor

#------------------------------------------------------------------------------
# Custom Configurations
#------------------------------------------------------------------------------
# Source custom configurations
source "$HOME/.dotfiles/zsh/aliases.zsh"
source "$HOME/.dotfiles/zsh/functions.zsh"

#------------------------------------------------------------------------------
# Bun config
#------------------------------------------------------------------------------
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export PATH=/Users/daniel/.cache/rebar3/bin:$PATH

# Source secrets if they exist
[ -f ~/.secrets ] && source ~/.secrets

# Source Powerlevel10k configuration
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
